/*2.STRUCTURAL DESIGN PATTERN ...  
 
 I>.FACADE PATTERN ... 
         //   like parcel at house door 
  basically whenever you have a lot of complex code and in many places we have to use the similar code what we'll do ... we'll create a function or a facade about it and without worring about what is is inside the function. 

//this kind of things (FACEDE PATTERN ) we have doing it since a lot of time..
     //eg .displaying data on dom ...
     //middlewares are one of the examples...

*/




  
/*   3.BEHAVIOURAL DESIGN PATTERN ...
    
I>. observer behavioural design pattern ...  
     //someone is observing a particular person... 
   
    eg...  yt
       upload  notifications (for subscribers).. 
     if (not) - >   manually checking(anyone) ...
codewith harry channel is observed by youtube... 

this is observer behavioural design pattern ...

*/